"""category name can't be nullable

Revision ID: 185b304f8479
Revises: 5d214430baeb
Create Date: 2024-04-01 14:07:45.092870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185b304f8479'
down_revision = '5d214430baeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
