"""Create suscriptions and topics table

Revision ID: 37b441ce8eb6
Revises: 185b304f8479
Create Date: 2024-04-01 15:58:29.174527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b441ce8eb6'
down_revision = '185b304f8479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['suscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
